version: '3.1'

services:
  test_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_USER: mwlk
      MYSQL_USER: mwlk
      MYSQL_ROOT_PASSWORD: Dicsys2022
      MYSQL_PASSWORD: Dicsys2022

